# Generated by Django 2.2 on 2019-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tram',
            name='mins_left',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
