# Generated by Django 2.2 on 2019-04-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signboard', '0002_tram_mins_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='line_color',
            field=models.CharField(default='red', max_length=24),
            preserve_default=False,
        ),
    ]
