# Generated by Django 2.2 on 2019-04-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signboard', '0003_line_line_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='line_text_color',
            field=models.CharField(default='#FFFFFF', max_length=24),
            preserve_default=False,
        ),
    ]
