# Generated by Django 2.2 on 2019-04-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signboard', '0004_line_line_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='delay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tram',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signboard.Line'),
        ),
    ]
