# Generated by Django 2.2 on 2019-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signboard', '0005_auto_20190424_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('shown', models.BooleanField()),
            ],
        ),
    ]
