# Generated by Django 2.2 on 2019-04-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signboard', '0006_signalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalert',
            name='shown',
            field=models.BooleanField(default=True),
        ),
    ]
