# Generated by Django 2.2 on 2019-04-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signboard', '0007_auto_20190424_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tram',
            old_name='remaining_seats',
            new_name='occupied_seats',
        ),
    ]
