# Generated by Django 2.2 on 2019-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signboard', '0008_auto_20190424_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('waiting', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
    ]
